### ISSUE TITLE
v6.0.0 breaks TypeScript with `--moduleResolution nodenext`

### ISSUE THREAD

**Issue by simon-abbott** [bendrucker/creditcards#75]
After updating to v6.0.0 I am now getting the following errors when trying to build:

```
../../node_modules/creditcards/index.d.ts:1:23 - error TS2835: Relative import paths need explicit file extensions in ECMAScript imports when '--moduleResolution' is 'node16' or 'nodenext'. Did you mean './card.js'?

1 import { ICard } from "./card";
                        ~~~~~~~~

../../node_modules/creditcards/index.d.ts:2:22 - error TS2835: Relative import paths need explicit file extensions in ECMAScript imports when '--moduleResolution' is 'node16' or 'nodenext'. Did you mean './cvc.js'?

2 import { ICvc } from "./cvc";
                       ~~~~~~~

../../node_modules/creditcards/index.d.ts:3:29 - error TS2835: Relative import paths need explicit file extensions in ECMAScript imports when '--moduleResolution' is 'node16' or 'nodenext'. Did you mean './expiration.js'?

3 import { IExpiration } from "./expiration";
                              ~~~~~~~~~~~~~~

../../node_modules/creditcards/index.d.ts:4:26 - error TS2835: Relative import paths need explicit file extensions in ECMAScript imports when '--moduleResolution' is 'node16' or 'nodenext'. Did you mean './types.js'?

4 import { CardType } from "./types";
                           ~~~~~~~~~
```
